# TF Configuration for automated_robot_planning
# This file contains optimized TF parameters to reduce timing errors

# Global TF parameters
tf2_ros:
  ros__parameters:
    # Reduce transform tolerance to be more strict about timing
    transform_tolerance: 0.5  # Reduced from 2.0 to 0.5 seconds
    
    # Buffer settings for TF2
    buffer_duration: 10.0  # How long to keep transforms in buffer
    
    # Cache timeout settings
    cache_timeout: 5.0  # How long to wait for transforms before timing out

# AMCL TF parameters (override the ones in shelfino.yaml)
amcl:
  ros__parameters:
    # Reduce transform tolerance for more precise timing
    transform_tolerance: 0.5  # Reduced from 2.0
    
    # Ensure TF broadcasting is enabled
    tf_broadcast: true
    publish_tf: true
    
    # Reduce update intervals for more frequent pose updates
    update_min_a: 0.1  # Reduced from 0.2
    update_min_d: 0.1  # Reduced from 0.25

# Navigation TF parameters
bt_navigator:
  ros__parameters:
    # Reduce transform tolerance for navigation
    transform_tolerance: 0.5  # Reduced from 2.0
    
    # Ensure proper frame configuration
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom

# Controller server TF parameters
controller_server:
  ros__parameters:
    # Reduce transform tolerance for controller
    transform_tolerance: 0.5  # Reduced from 1.0
    
    # Increase controller frequency for more responsive behavior
    controller_frequency: 30.0  # Increased from 20.0

# Local costmap TF parameters
local_costmap:
  ros__parameters:
    # Reduce transform tolerance for local costmap
    transform_tolerance: 0.5
    
    # Ensure proper frame configuration
    global_frame: odom
    robot_base_frame: base_link
    map_topic: /map
    subscribe_to_updates: true

# Global costmap TF parameters
global_costmap:
  ros__parameters:
    # Reduce transform tolerance for global costmap
    transform_tolerance: 0.5
    
    # Ensure proper frame configuration
    global_frame: map
    robot_base_frame: base_link
    map_topic: /map
    subscribe_to_updates: true

# Behavior tree navigator TF parameters
bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    # Reduce transform tolerance for behavior tree
    transform_tolerance: 0.5

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    # Reduce transform tolerance for behavior tree
    transform_tolerance: 0.5

# QoS Bridge specific parameters
qos_bridge:
  ros__parameters:
    # TF timing tolerance for the QoS bridge
    tf_tolerance: 0.1  # 100ms tolerance for TF validation
    
    # Enable timestamp validation
    enable_timestamp_validation: true
    
    # Enable timestamp correction
    enable_timestamp_correction: true 