<?xml version='1.0' ?>
<robot name='shelfino' xmlns:xacro='http://www.ros.org/wiki/xacro'>  
  <gazebo>
    <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
      <update_rate>50</update_rate>
      <!-- Wheel info -->
      <left_joint>shelfino${robot_id}/left_wheel_joint</left_joint>
      <right_joint>shelfino${robot_id}/right_wheel_joint</right_joint>
      <wheel_separation>${body_width+0.04}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <!-- Limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <max_linear_acceleration>0.033</max_linear_acceleration> 

      <topic>shelfino${robot_id}cmd_vel</topic>

      <!-- Output -->
      <odom_topic>shelfino${robot_id}/odom</odom_topic>
      <frame_id>shelfino${robot_id}/odom</frame_id> <!-- from <odometry_frame> -->
      <child_frame_id>shelfino${robot_id}/base_link</child_frame_id> <!-- from <robot_base_frame> -->
      <odom_publisher_frequency>50</odom_publisher_frequency> <!-- from <update_rate>-->

      <tf_topic>/tf</tf_topic> 
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_wheel_transform>true</publish_wheel_transform>
    </plugin>
  </gazebo> 
</robot>